name: Question
description: 使用疑问或行为确认
title: "question: "
labels: [question]
body:
  - type: textarea
    id: question
    attributes:
      label: 问题
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 上下文（配置 / 日志）
      description: 相关配置请脱敏，日志请贴关键部分。
      render: shell
    validations:
      required: false
